// Credential Type
export const CredentialSubtypes = [
  "ceterms:ApprenticeshipCertificate",
  "ceterms:AssociateDegree",
  "ceterms:BachelorDegree",
  "ceterms:Badge",
  "ceterms:Certificate",
  "ceterms:Certification",
  "ceterms:CertificateOfCompletion",
  "ceterms:Degree",
  "ceterms:DigitalBadge",
  "ceterms:Diploma",
  "ceterms:DoctoralDegree",
  "ceterms:GeneralEducationDevelopment",
  "ceterms:JourneymanCertificate",
  "ceterms:License",
  "ceterms:MasterCertificate",
  "ceterms:MasterDegree",
  "ceterms:MicroCredential",
  "ceterms:OpenBadge",
  "ceterms:ProfessionalDoctorate",
  "ceterms:QualityAssuranceCredential",
  "ceterms:ResearchDoctorate",
  "ceterms:SecondarySchoolDiploma",
];
